### ISSUE TITLE
Cannot open Pragha

### ISSUE THREAD

**Issue by glaubersm** [flathub/io.github.pragha_music_player.pragha#23]
Hi

I use Arch linux, I can't open Pragha. I get this output in a terminal:

```
$ flatpak run io.github.pragha_music_player.pragha
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

```

**Comment by JaneSmith** [comment]
Same issue here.

**Comment by JaneSmith** [comment]
Using Flatseal to add the `socket=session-bus` permission lets the app launch.

**Comment by Mailaender** [comment]
Flathub staff probably won't allow for the whole `socket=session-bus` so we need to find the new talk id and add that to the manifest.

**Comment by Mailaender** [comment]
My bet is on `io.github.pragha_music_player` https://github.com/flathub/io.github.pragha_music_player.pragha/blob/6725874839f7d7d87ad84e2d03e5c2804f972e57/io.github.pragha_music_player.pragha.yml#L160

**Comment by glaubersm** [comment]
Today's update has fixed Pragha on my system. Thank you all.
